### ISSUE TITLE
Food Provider Reviews View

### ISSUE THREAD

**Issue by MichaelKMalak** [FreshOver/cheffresh#13]
- View Food Provider name, picture, and general rating
- View other user's reviews (text) and rating (Stars) for a certain food provider
- View every review date created

**Comment by WahdanZ** [comment]
where is the UI for this view

**Comment by MichaelKMalak** [comment]
We didn't have time to make a UI for it.
It's basically a form for this table https://github.com/FreshOver/cheffresh#reviews

**Comment by MichaelKMalak** [comment]
btw, this is just a view that appears when the user clicks on "view more reviews from this food provider"
There is another view to add a review here https://github.com/FreshOver/cheffresh/issues/15.
will you take that case?
